### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by useybrain** [TMRJIJ/Night-Shift-on-Unsupported-Macs#1]
AFTER disabling SIP
Enable NightShift.sh: Permission denied
?

**Comment by TMRJIJ** [comment]
You must run the script as an administrator. Type: sudo then drag the script.

**Comment by useybrain** [comment]
"Enable NightShift.sh: command not found"

**Comment by vandroiy2013** [comment]
sudo -s
password
sh /Users/user_name/Downloads/Enable\ NightShift.sh

**Comment by useybrain** [comment]
yep, I do it several times
"
iMac-Sebastian:~ sebastian$ sudo -s
Password:
bash-3.2# /Volumes/HDD/Tools/\!\ start.mac/Enable\ NightShift.sh 
bash: /Volumes/HDD/Tools/! start.mac/Enable NightShift.sh: Permission denied
bash-3.2# 
"

**Comment by vandroiy2013** [comment]
Read carefully!!!!
**sh** /Users/user_name/Downloads/Enable\ NightShift.sh

**Comment by ghost** [comment]
Didn't work for me either.

Try [this patch](https://github.com/pookjw/NightPatch), worked for me.

**Comment by TMRJIJ** [comment]
You can try [pookjw's patch](https://github.com/pookjw/NightPatch) or use[ foxlet's AppleScript Applet](https://forums.macrumors.com/threads/macos-10-12-sierra-unsupported-macs-thread.1977128/page-181#post-24439821). The Applet does the exact same thing as my script but you won't need to play with the terminal.

**Comment by useybrain** [comment]
rafuse: WORK perfect! THX a lot!
