### ISSUE TITLE
Isn't this illegal?

### ISSUE THREAD

**Issue by guowgd** [TMRJIJ/Night-Shift-on-Unsupported-Macs#2]
Seems like you uploaded macOS file system to your GitHub, and server.

https://github.com/TMRJIJ/Night-Shift-on-Unsupported-Macs/tree/master/Resources/CoreBrightness.framework

http://dosdude1.com/sierra/NightShiftPatch/CoreBrightness.framework.zip

Isn't this illegal?

**Comment by guowgd** [comment]
... and seems like you're trying to replace 10.12.4 system file to 10.12.5. I think it is really dangerous. This method will stuck macOS.

**Comment by TMRJIJ** [comment]
It does violate Apple's Software Guidelines (Section M), but certainly nobody will get 'arrested' for using this script.
The framework, besides recompiling from Beta Updates, hasn't changed as far as where the model checks are. 
I will continue to keep this repository up-to-date if changes do occur. 
As such, the worst I seen from failures to codesign the brightness framework during early testing was the Display Tab in System Preferences crashing. Other than that, the Macs were still functioning properly. Of course, the script and GUI Installer both create backups of the original framework just in case.

**Comment by seanbperiod** [comment]
I'm curious how this will respond after a macOS update.. will it be overwritten/removed? or will it cause the install to hang?

**Comment by TMRJIJ** [comment]
It will be overwritten. You can use the script/Installer again to re-enable the Night Shift feature.
