### ISSUE TITLE
Doesn't work with `csrutil enable --without fs`.

### ISSUE THREAD

**Issue by pookjw** [TMRJIJ/Night-Shift-on-Unsupported-Macs#3]
![Image1](https://farm5.staticflickr.com/4196/34726061461_e2b2671237_o.jpg)

![Image2](https://farm5.staticflickr.com/4170/34726077271_ecb9d1d9b1_o.png)

![Image3](https://farm5.staticflickr.com/4204/34014782864_b180489d4c_o.png)

Seems like your script doesn't work with `$ csrutil enable --without fs`.

**Comment by TMRJIJ** [comment]
I'll look into that today. Thanks for letting me know, Kim.  :)

**Comment by TMRJIJ** [comment]
I believe this issue is resolved now.
