### ISSUE TITLE
Night Shift broke OSX

### ISSUE THREAD

**Issue by ilyacherevkov** [TMRJIJ/Night-Shift-on-Unsupported-Macs#7]
After I installed Night Shift on 10.13.6 on Macbook Air 13' 2011, OSX stopped working and loading. Needed to perform Recovery to fix things.

**Comment by ilyacherevkov** [comment]
I was stuck on login screen, with Dialog Message "Connect Bluetooth Keyboard". Mouse and keyboard were unresponsive though and Bluetooth keyboard couldn't connect.

**Comment by TMRJIJ** [comment]
Patch has been updated and should fix this issue. Sorry for the long absense.
