### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by SpiraMira** [TMRJIJ/Night-Shift-on-Unsupported-Macs#8]
Hi - I cited as you as an inspirational reference for some Mojave Light mode patches (for unsupported machines) I am working on.  

I have a private repo addressing them and would like to invite you.  Do you have an email associated with this account.  osx-hackers seems to be down.  Look out for an invite but would like chat...I'm on dosdude1's  Mojave Unsupported macrumors forum too.

**Comment by TMRJIJ** [comment]
Hey, 

Sorry about the long response. I just haven't really been available to really work on any project on account of my last year in College. Are you still working on Mojave Light Mode patches?

Isiah Johnson

**Comment by SpiraMira** [comment]
No problem.  And yes still reverse-engineering and patching the IU :-)

Patrice
